### ISSUE TITLE
Duplicate README in repository

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITKThinShellDemons#1]
The repository contains two `README` files at the root level, one in `Markdown` format and the other one in `reStrucuredText` format. This is not common across the `InsightSoftwareConsortium` organization or `ITK`'s remote modules.

A single `README` file should probably exist.

**Comment by jhlegarreta** [comment]
@samuelgerber would you please have a look at this as time permits? Thanks.

**Comment by jhlegarreta** [comment]
@samuelgerber Below are the differences across the `Markdown` and the `reStrucuredText` files:

In section `# ITKThinShellDemons`, `md` file:
> :warning: **This module requires to be compiled against an ITK version with**  
> - [PointSetToPointSetMetricWithIndexv4](https://github.com/InsightSoftwareConsortium/ITK/pull/2385)   
> 
> If you are compiling against an older version  use the ones inlcuded in this repository marked with h/hxx-unused (remove the -unused).

In section `## V4 version (TSHDv4)`, `rst` file:
> **The implementation currently supports the thin shell regularization. Missing features are a 
confidence matching weighting and geometric feature matching (currently only point distances 
are used).**

In section `## Original version (TSHD)`, `rst` file:

> **The implementation supports the thin shell regularization, geometric feature matching
(currently updated at each iteration during optimization). Missing features are a
confidence matching weighting.**


Would you please tell which parts are to be kept/removed so that a single `README` exists ? Thanks !

**Comment by dzenanz** [comment]
Considering c957ce18e3d47970f85275c78d3fd74308bc4a32 and b7e99b85ca18b43f11e0a0041835add0094bc1da, I think that the more advanced version of docs is the correct one. Scratch that - there are both the old and new version. I think that .rst file should just be deleted, as it is older.

**Comment by jhlegarreta** [comment]
> Considering c957ce1 and b7e99b8, I think that the more advanced version of docs is the correct one. Scratch that - there are both the old and new version. I think that .rst file should just be deleted, as it is older.

Sounds reasonable considering the commits. Thanks @dzenanz .
