### ISSUE TITLE
Update the Python package dependency version

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKThinShellDemons#12]
https://github.com/InsightSoftwareConsortium/ITKThinShellDemons/blob/62d4fe3a3519baaeee7ed865e8e652b206b64399/setup.py#L46

to `v5.2.0.post2`

**Comment by thewtex** [comment]
@PranjalSahu we should now use 5.3rc3

**Comment by PranjalSahu** [comment]
https://github.com/InsightSoftwareConsortium/ITKThinShellDemons/pull/18
