### ISSUE TITLE
Errors during testing with ITK_DISALLOW_COPY_AND_MOVE

### ISSUE THREAD

**Issue by tapphughesn** [InsightSoftwareConsortium/ITKThinShellDemons#4]
Hi there, I am getting errors while trying to build and make ITKThinShellDemons. I am using Ubuntu 18.04 and I built TSD using ccmake version 3.20.2. When I "make", I get the error log below.

<pre><font color="#8AE234"><b>nick@nick-MS-7C02</b></font>$ make
[  0%] Built target ITKData
[ 32%] Built target ClangFormat
[ 64%] Built target KWStyle
<font color="#AD7FA8"><b>Consolidate compiler generated dependencies of target ThinShellDemonsTestDriver</b></font>
[ 68%] <font color="#4E9A06">Building CXX object test/CMakeFiles/ThinShellDemonsTestDriver.dir/itkThinShellDemonsTest.cxx.o</font>
In file included from <b>/home/nick/Downloads/ITKThinShellDemons/include/itkThinShellDemonsMetric.h:21:0</b>,
                 from <b>/home/nick/Downloads/ITKThinShellDemons/test/itkThinShellDemonsTest.cxx:22</b>:
<b>/home/nick/Downloads/ITKThinShellDemons/include/itkMeshToMeshMetric.h:46:46:</b> <font color="#EF2929"><b>error: </b></font>ISO C++ forbids declaration of ‘<b>ITK_DISALLOW_COPY_AND_MOVE</b>’ with no type [<font color="#EF2929"><b>-fpermissive</b></font>]
   ITK_DISALLOW_COPY_AND_MOVE(MeshToMeshMetric<font color="#EF2929"><b>)</b></font>;
                                              <font color="#EF2929"><b>^</b></font>
<b>/home/nick/Downloads/ITKThinShellDemons/include/itkMeshToMeshMetric.h:125:3:</b> <font color="#AD7FA8"><b>warning: </b></font>dynamic exception specifications are deprecated in C++11 [<font color="#AD7FA8"><b>-Wdeprecated</b></font>]
   <font color="#AD7FA8"><b>throw</b></font> ( ExceptionObject );
   <font color="#AD7FA8"><b>^~~~~</b></font>
In file included from <b>/home/nick/Downloads/ITKThinShellDemons/include/itkMeshToMeshMetric.h:142:0</b>,
                 from <b>/home/nick/Downloads/ITKThinShellDemons/include/itkThinShellDemonsMetric.h:21</b>,
                 from <b>/home/nick/Downloads/ITKThinShellDemons/test/itkThinShellDemonsTest.cxx:22</b>:
<b>/home/nick/Downloads/ITKThinShellDemons/include/itkMeshToMeshMetric.hxx:53:1:</b> <font color="#AD7FA8"><b>warning: </b></font>dynamic exception specifications are deprecated in C++11 [<font color="#AD7FA8"><b>-Wdeprecated</b></font>]
 <font color="#AD7FA8"><b>throw</b></font> ( ExceptionObject )
 <font color="#AD7FA8"><b>^~~~~</b></font>
In file included from <b>/home/nick/Downloads/ITKThinShellDemons/include/itkThinShellDemonsMetric.h:25:0</b>,
                 from <b>/home/nick/Downloads/ITKThinShellDemons/test/itkThinShellDemonsTest.cxx:22</b>:
<b>/home/nick/Downloads/ITKThinShellDemons/include/itkMeshTovtkPolyData.h:44:50:</b> <font color="#EF2929"><b>error: </b></font>ISO C++ forbids declaration of ‘<b>ITK_DISALLOW_COPY_AND_MOVE</b>’ with no type [<font color="#EF2929"><b>-fpermissive</b></font>]
   ITK_DISALLOW_COPY_AND_MOVE(itkMeshTovtkPolyData<font color="#EF2929"><b>)</b></font>;
                                                  <font color="#EF2929"><b>^</b></font>
In file included from <b>/home/nick/Downloads/ITKThinShellDemons/test/itkThinShellDemonsTest.cxx:22:0</b>:
<b>/home/nick/Downloads/ITKThinShellDemons/include/itkThinShellDemonsMetric.h:55:51:</b> <font color="#EF2929"><b>error: </b></font>ISO C++ forbids declaration of ‘<b>ITK_DISALLOW_COPY_AND_MOVE</b>’ with no type [<font color="#EF2929"><b>-fpermissive</b></font>]
   ITK_DISALLOW_COPY_AND_MOVE(ThinShellDemonsMetric<font color="#EF2929"><b>)</b></font>;
                                                   <font color="#EF2929"><b>^</b></font>
<b>/home/nick/Downloads/ITKThinShellDemons/include/itkThinShellDemonsMetric.h:110:33:</b> <font color="#AD7FA8"><b>warning: </b></font>dynamic exception specifications are deprecated in C++11 [<font color="#AD7FA8"><b>-Wdeprecated</b></font>]
   virtual void Initialize(void) <font color="#AD7FA8"><b>throw</b></font> ( ExceptionObject ) ITK_OVERRIDE;
                                 <font color="#AD7FA8"><b>^~~~~</b></font>
In file included from <b>/home/nick/Downloads/ITKThinShellDemons/include/itkThinShellDemonsMetric.h:224:0</b>,
                 from <b>/home/nick/Downloads/ITKThinShellDemons/test/itkThinShellDemonsTest.cxx:22</b>:
<b>/home/nick/Downloads/ITKThinShellDemons/include/itkThinShellDemonsMetric.hxx:54:1:</b> <font color="#AD7FA8"><b>warning: </b></font>dynamic exception specifications are deprecated in C++11 [<font color="#AD7FA8"><b>-Wdeprecated</b></font>]
 <font color="#AD7FA8"><b>throw</b></font> ( ExceptionObject )
 <font color="#AD7FA8"><b>^~~~~</b></font>
In file included from <b>/home/nick/Downloads/ITKThinShellDemons/test/itkThinShellDemonsTest.cxx:24:0</b>:
<b>/home/nick/Downloads/ITKThinShellDemons/include/itkMeshToMeshRegistrationMethod.h:35:58:</b> <font color="#EF2929"><b>error: </b></font>ISO C++ forbids declaration of ‘<b>ITK_DISALLOW_COPY_AND_MOVE</b>’ with no type [<font color="#EF2929"><b>-fpermissive</b></font>]
   ITK_DISALLOW_COPY_AND_MOVE(MeshToMeshRegistrationMethod<font color="#EF2929"><b>)</b></font>;
                                                          <font color="#EF2929"><b>^</b></font>
<b>/home/nick/Downloads/ITKThinShellDemons/include/itkMeshToMeshRegistrationMethod.h:108:3:</b> <font color="#AD7FA8"><b>warning: </b></font>dynamic exception specifications are deprecated in C++11 [<font color="#AD7FA8"><b>-Wdeprecated</b></font>]
   <font color="#AD7FA8"><b>throw</b></font> ( ExceptionObject );
   <font color="#AD7FA8"><b>^~~~~</b></font>
In file included from <b>/home/nick/Downloads/ITKThinShellDemons/include/itkMeshToMeshRegistrationMethod.h:164:0</b>,
                 from <b>/home/nick/Downloads/ITKThinShellDemons/test/itkThinShellDemonsTest.cxx:24</b>:
<b>/home/nick/Downloads/ITKThinShellDemons/include/itkMeshToMeshRegistrationMethod.hxx:56:3:</b> <font color="#AD7FA8"><b>warning: </b></font>dynamic exception specifications are deprecated in C++11 [<font color="#AD7FA8"><b>-Wdeprecated</b></font>]
   <font color="#AD7FA8"><b>throw</b></font> ( ExceptionObject )
   <font color="#AD7FA8"><b>^~~~~</b></font>
In file included from <b>/home/nick/Downloads/ITKThinShellDemons/test/itkThinShellDemonsTest.cxx:25:0</b>:
<b>/home/nick/Downloads/ITKThinShellDemons/include/itkMeshDisplacementTransform.h:49:55:</b> <font color="#EF2929"><b>error: </b></font>ISO C++ forbids declaration of ‘<b>ITK_DISALLOW_COPY_AND_MOVE</b>’ with no type [<font color="#EF2929"><b>-fpermissive</b></font>]
   ITK_DISALLOW_COPY_AND_MOVE(MeshDisplacementTransform<font color="#EF2929"><b>)</b></font>;
                                                       <font color="#EF2929"><b>^</b></font>
In file included from <b>/home/nick/Downloads/ITKThinShellDemons/include/itkThinShellDemonsMetric.h:21:0</b>,
                 from <b>/home/nick/Downloads/ITKThinShellDemons/test/itkThinShellDemonsTest.cxx:22</b>:
/home/nick/Downloads/ITKThinShellDemons/include/itkMeshToMeshMetric.h: In instantiation of ‘<b>class itk::MeshToMeshMetric&lt;itk::Mesh&lt;double, 3&gt;, itk::Mesh&lt;double, 3&gt; &gt;</b>’:
<b>/home/nick/Downloads/ITKThinShellDemons/include/itkThinShellDemonsMetric.h:51:27:</b>   required from ‘<b>class itk::ThinShellDemonsMetric&lt;itk::Mesh&lt;double, 3&gt; &gt;</b>’
<b>/home/nick/Downloads/ITKThinShellDemons/test/itkThinShellDemonsTest.cxx:90:13:</b>   required from here
<b>/home/nick/Downloads/ITKThinShellDemons/include/itkMeshToMeshMetric.h:46:3:</b> <font color="#EF2929"><b>error: </b></font>invalid abstract parameter type ‘<b>itk::MeshToMeshMetric&lt;itk::Mesh&lt;double, 3&gt;, itk::Mesh&lt;double, 3&gt; &gt;</b>’
   <font color="#EF2929"><b>ITK_DISALLOW_COPY_AND_MOVE</b></font>(MeshToMeshMetric);
   <font color="#EF2929"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
<b>/home/nick/Downloads/ITKThinShellDemons/include/itkMeshToMeshMetric.h:43:27:</b> <font color="#34E2E2"><b>note: </b></font><b>  because the following virtu</b>al functions are pure within ‘<b>itk::MeshToMeshMetric&lt;itk::Mesh&lt;double, 3&gt;, itk::Mesh&lt;double, 3&gt; &gt;</b>’:
 class ITK_TEMPLATE_EXPORT <font color="#34E2E2"><b>MeshToMeshMetric</b></font>:public SingleValuedCostFunction
                           <font color="#34E2E2"><b>^~~~~~~~~~~~~~~~</b></font>
In file included from <b>/home/nick/Downloads/ITKThinShellDemons/include/itkMeshToMeshMetric.h:24:0</b>,
                 from <b>/home/nick/Downloads/ITKThinShellDemons/include/itkThinShellDemonsMetric.h:21</b>,
                 from <b>/home/nick/Downloads/ITKThinShellDemons/test/itkThinShellDemonsTest.cxx:22</b>:
<b>/home/nick/Downloads/InsightToolkit-5.1.2/Modules/Numerics/Optimizers/include/itkSingleValuedCostFunction.h:64:3:</b> <font color="#34E2E2"><b>note: </b></font>	virtual itk::SingleValuedCostFunction::MeasureType itk::SingleValuedCostFunction::GetValue(const ParametersType&amp;) const
   <font color="#34E2E2"><b>GetValue</b></font>(const ParametersType &amp; parameters) const = 0;
   <font color="#34E2E2"><b>^~~~~~~~</b></font>
<b>/home/nick/Downloads/InsightToolkit-5.1.2/Modules/Numerics/Optimizers/include/itkSingleValuedCostFunction.h:69:3:</b> <font color="#34E2E2"><b>note: </b></font>	virtual void itk::SingleValuedCostFunction::GetDerivative(const ParametersType&amp;, itk::SingleValuedCostFunction::DerivativeType&amp;) const
   <font color="#34E2E2"><b>GetDerivative</b></font>(const ParametersType &amp; parameters, DerivativeType &amp; derivative) const = 0;
   <font color="#34E2E2"><b>^~~~~~~~~~~~~</b></font>
test/CMakeFiles/ThinShellDemonsTestDriver.dir/build.make:89: recipe for target &apos;test/CMakeFiles/ThinShellDemonsTestDriver.dir/itkThinShellDemonsTest.cxx.o&apos; failed
make[2]: *** [test/CMakeFiles/ThinShellDemonsTestDriver.dir/itkThinShellDemonsTest.cxx.o] Error 1
CMakeFiles/Makefile2:1049: recipe for target &apos;test/CMakeFiles/ThinShellDemonsTestDriver.dir/all&apos; failed
make[1]: *** [test/CMakeFiles/ThinShellDemonsTestDriver.dir/all] Error 2
Makefile:145: recipe for target &apos;all&apos; failed
make: *** [all] Error 2
</pre>

All of the errors have come from `ITK_DISALLOW_COPY_AND_MOVE(*)`

What should I do to fix it? Thanks

**Comment by dzenanz** [comment]
You should use a newer version of ITK. [ITK_DISALLOW_COPY_AND_MOVE](https://github.com/InsightSoftwareConsortium/ITK/pull/2053) macro was added recently.

**Comment by tapphughesn** [comment]
Thank you so much!
