### ISSUE TITLE
Using ThinShellDemons in an external project?

### ISSUE THREAD

**Issue by tapphughesn** [InsightSoftwareConsortium/ITKThinShellDemons#5]
Hello, I am a student who wants to use TSD in an external project. I am simply trying to create an executable which does surface registration as in [ITKThinShellDemons/test/itkThinShellDemonsTest.cxx](https://github.com/InsightSoftwareConsortium/ITKThinShellDemons/blob/main/test/itkThinShellDemonsTest.cxx) . This is my CMakeLists.txt :

```
cmake_minimum_required(VERSION 3.10)

# set the project name
project(Tsdproj)

find_package(VTK REQUIRED)
find_package(ITK REQUIRED)

include(${ITK_USE_FILE})
include(${VTK_USE_FILE})

# add the executable
add_executable(Tsdproj Tsdproj.cxx)

target_link_libraries(Tsdproj ITKThinShellDemons)
target_link_libraries(Tsdproj ${VTK_LIBRARIES})
target_link_libraries(Tsdproj ${ITK_LIBRARIES})

target_include_directories(Tsdproj PUBLIC
                          "${PROJECT_BINARY_DIR}"
                          "${PROJECT_SOURCE_DIR}/../../ITKThinShellDemons"
                          )
```

When I generate and make, I get the following error:

<pre><font color="#8AE234"><b>nick@nick-MS-7C02</b></font>:<font color="#729FCF"><b>Tsdproj-build</b></font>$ make
[ 50%] <font color="#4E9A06">Building CXX object CMakeFiles/Tsdproj.dir/Tsdproj.cxx.o</font>
<b>/home/nick/Documents/classwork_20_21/COMP766/course_project/Tsdproj/Tsdproj.cxx:5:10:</b> <font color="#EF2929"><b>fatal error: </b></font>itkThinShellDemonsMetric.h: No such file or directory
 #include <font color="#EF2929"><b>&quot;itkThinShellDemonsMetric.h&quot;</b></font>
          <font color="#EF2929"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
compilation terminated.
CMakeFiles/Tsdproj.dir/build.make:75: recipe for target &apos;CMakeFiles/Tsdproj.dir/Tsdproj.cxx.o&apos; failed
make[2]: *** [CMakeFiles/Tsdproj.dir/Tsdproj.cxx.o] Error 1
CMakeFiles/Makefile2:82: recipe for target &apos;CMakeFiles/Tsdproj.dir/all&apos; failed
make[1]: *** [CMakeFiles/Tsdproj.dir/all] Error 2
Makefile:90: recipe for target &apos;all&apos; failed
make: *** [all] Error 2
</pre>

TSD isn't a "library" because there is no `ThinShellDemonsConfig.cmake`, right? What's the proper way to do this?

**Comment by dzenanz** [comment]
The proper way is to compile ITK, then compile ThinShellDemons pointing to that ITK build, then compile your Tsdproj pointing to that same ITK build.

When you build a remote module and point to an ITK build, that remote module gets "registered" there so it is available for applications.

**Comment by tapphughesn** [comment]
Thanks for your reply--I altered my CMakeLists.txt accordingly. I now have my TSD build and my Tsdproj build pointing to the same ITK build. I still get the exact same error as above when I compile. My .cxx file looks like:

```
#include <cstdlib>

#include "itkVTKPolyDataReader.h"
#include "itkVTKPolyDataWriter.h"
#include "itkThinShellDemonsMetric.h"
#include "itkLBFGSOptimizer.h"
#include "itkMeshToMeshRegistrationMethod.h"
#include "itkMeshDisplacementTransform.h"
#include "itkConjugateGradientOptimizer.h"

int main(int argc, char* argv[])
{
  return 0;
}
```

I get no errors on `#include "itkVTKPolyDataReader.h"`, so I know Tsdproj can see ITK. Is there something else I am missing? Do I need to put the ITKThinShellDemons module in my ITK source tree? Thanks again for your help.

**Comment by dzenanz** [comment]
Does doing an [explicit components list](https://github.com/KitwareMedical/HASI/blob/0b876b304eb73a63acb70c015706af8f3887e227/examples/CMakeLists.txt#L16) help?

**Comment by tapphughesn** [comment]
With this CMakeLists.txt: 

```
cmake_minimum_required(VERSION 3.10)

# set the project name
project(Tsdproj)


find_package(ITK REQUIRED)
find_package(ITK 5 REQUIRED
			 COMPONENTS
			 ITKThinShellDemons)

include(${ITK_USE_FILE})

# add the executable
add_executable(Tsdproj Tsdproj.cxx)

target_link_libraries(Tsdproj ${ITK_LIBRARIES})

```

I get this CMake Error:

<pre>CMake Error at /home/nick/Documents/classwork_20_21/COMP766/ITK/CMake/ITKModuleAPI.cmake:78
 (message):
   No such module: &quot;ITKThinShellDemons&quot;
 Call Stack (most recent call first):
   /home/nick/Documents/classwork_20_21/COMP766/ITK/CMake/ITKModuleAPI.cmake:31 (itk_module_load)
   /home/nick/Documents/classwork_20_21/COMP766/ITK/CMake/ITKModuleAPI.cmake:129
 (_itk_module_config_recurse)
   /home/nick/Documents/classwork_20_21/COMP766/ITK-build/ITKConfig.cmake:86 (itk_module_config)
   CMakeLists.txt:8 (find_package)

 Configuring incomplete, errors occurred!
 See also
 &quot;/home/nick/Documents/classwork_20_21/COMP766/course_project/Tsdproj-build/CMakeFiles/CMakeOutput.log
 &quot;.
 See also
 &quot;/home/nick/Documents/classwork_20_21/COMP766/course_project/Tsdproj-build/CMakeFiles/CMakeError.log&quot;
 .
</pre>


EDIT: I changed `ITKThinShellDemons` to `ThinShellDemons` and got the following error when compiling:

<pre>[100%] <font color="#8AE234"><b>Linking CXX executable Tsdproj</b></font>
/usr/bin/ld: cannot find -lITKCommon
/usr/bin/ld: cannot find -lITKMesh
/usr/bin/ld: cannot find -lITKOptimizersv4
/usr/bin/ld: cannot find -lITKStatistics
/usr/bin/ld: cannot find -lITKTransform
/usr/bin/ld: cannot find -lITKSpatialObjects
/usr/bin/ld: cannot find -lITKPath
/usr/bin/ld: cannot find -lITKSmoothing
/usr/bin/ld: cannot find -lITKImageFeature
/usr/bin/ld: cannot find -lITKOptimizers
/usr/bin/ld: cannot find -lITKRegistrationMethodsv4
/usr/bin/ld: cannot find -lITKVtkGlue
/usr/bin/ld: cannot find -litksys
/usr/bin/ld: cannot find -litkvnl_algo
/usr/bin/ld: cannot find -litkvnl
/usr/bin/ld: cannot find -litkv3p_netlib
/usr/bin/ld: cannot find -litkvcl
/usr/bin/ld: cannot find -litkNetlibSlatec
/usr/bin/ld: cannot find -lITKMetaIO
/usr/bin/ld: cannot find -litkzlib
/usr/bin/ld: cannot find -lITKVTK
collect2: error: ld returned 1 exit status
CMakeFiles/Tsdproj.dir/build.make:227: recipe for target &apos;Tsdproj&apos; failed
make[2]: *** [Tsdproj] Error 1
CMakeFiles/Makefile2:82: recipe for target &apos;CMakeFiles/Tsdproj.dir/all&apos; failed
make[1]: *** [CMakeFiles/Tsdproj.dir/all] Error 2
Makefile:90: recipe for target &apos;all&apos; failed
make: *** [all] Error 2
</pre>

**Comment by dzenanz** [comment]
Module name should be [`ThinShellDemons`](https://github.com/InsightSoftwareConsortium/ITKThinShellDemons/blob/main/itk-module.cmake#L14), not `ITKThinShellDemons`. You will also need other modules needed by your headers, such as `VtkGlue` and `ITKOptimizers`.

**Comment by tapphughesn** [comment]
When I use this CMakeLists.txt

```
cmake_minimum_required(VERSION 3.10)

# set the project name
project(Tsdproj)

find_package(VTK REQUIRED)
# find_package(ITK 5 REQUIRED)
find_package(ITK 5 REQUIRED
			COMPONENTS
			ThinShellDemons
			ITKVtkGlue
			ITKOptimizers
			ITKOptimizersv4
			ITKStatistics
			ITKTransform
			ITKSpatialObjects
			ITKPath
			ITKSmoothing
			ITKImageFeature
			ITKOptimizers
			ITKRegistrationMethodsv4
			ITKVtkGlue
			ITKMetaIO
			ITKVTK
)

include(${ITK_USE_FILE})

# add the executable
add_executable(Tsdproj Tsdproj.cxx)

target_link_libraries(Tsdproj ${VTK_LIBRARIES})
target_link_libraries(Tsdproj ${ITK_LIBRARIES})

```

Then I get these linker errors:

<pre>[100%] <font color="#8AE234"><b>Linking CXX executable Tsdproj</b></font>
/usr/bin/ld: cannot find -lITKCommon
/usr/bin/ld: cannot find -lITKMesh
/usr/bin/ld: cannot find -lITKOptimizersv4
/usr/bin/ld: cannot find -lITKStatistics
/usr/bin/ld: cannot find -lITKTransform
/usr/bin/ld: cannot find -lITKSpatialObjects
/usr/bin/ld: cannot find -lITKPath
/usr/bin/ld: cannot find -lITKSmoothing
/usr/bin/ld: cannot find -lITKImageFeature
/usr/bin/ld: cannot find -lITKOptimizers
/usr/bin/ld: cannot find -lITKRegistrationMethodsv4
/usr/bin/ld: cannot find -lITKVtkGlue
/usr/bin/ld: cannot find -litksys
/usr/bin/ld: cannot find -litkvnl_algo
/usr/bin/ld: cannot find -litkvnl
/usr/bin/ld: cannot find -litkv3p_netlib
/usr/bin/ld: cannot find -litkvcl
/usr/bin/ld: cannot find -litkNetlibSlatec
/usr/bin/ld: cannot find -lITKMetaIO
/usr/bin/ld: cannot find -litkzlib
/usr/bin/ld: cannot find -lITKVTK
collect2: error: ld returned 1 exit status
CMakeFiles/Tsdproj.dir/build.make:227: recipe for target &apos;Tsdproj&apos; failed
make[2]: *** [Tsdproj] Error 1
CMakeFiles/Makefile2:82: recipe for target &apos;CMakeFiles/Tsdproj.dir/all&apos; failed
make[1]: *** [CMakeFiles/Tsdproj.dir/all] Error 2
Makefile:90: recipe for target &apos;all&apos; failed
make: *** [all] Error 2
</pre>

Any idea why these might be occurring? The ITK_DIR cmake variable is set.

**Comment by dzenanz** [comment]
It should be working. Make sure you are pointing to the right build directory of ITK, and that ITK is fully and successfully compiled.

**Comment by dzenanz** [comment]
Do ITK examples (e.g. [ConvertAnRGBitkImageTovtkImageData](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/tree/master/src/Bridge/VtkGlue/ConvertAnRGBitkImageTovtkImageData)) work for you?

**Comment by tapphughesn** [comment]
@dzenanz Thank you so much! I created an ITK Hello World project, and I realized that my ITK build was not fully built. I could have sworn I fully built it before, but apparently not. Re-building ITK fixed my issues. You are a huge help! Hopefully I wont need to open any more issues...
