### ISSUE TITLE
Fix CI by adding a VTK build

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITKThinShellDemons#7]
Building VtkGlue in remote CI tests should be possible. Before build ITK step add a "build VTK step", and then add `-DModule_ITKVtkGlue:BOOL=ON` and `-DVTK_DIR:PATH=/path/to/vtk/build` to ITK configure line. If the latest VTK is problematic, we can use version 8.2 or whichever one works best. We can also trim down the VTK build by reducing number of requested modules, so it builds faster.

**Comment by dzenanz** [comment]
@PranjalSahu

**Comment by jcfr** [comment]
> VTK build

Few weeks ago, I discussed with @mathstuf adding support for publishing the VTK SDK on a weekly (or daily) basis. We should finalize this step, this is now tracked by https://gitlab.kitware.com/vtk/vtk/-/issues/18257

**Comment by PranjalSahu** [comment]
Closing this issue. Handled in https://github.com/InsightSoftwareConsortium/ITKThinShellDemons/pull/11
